create mysql insert query for  movies_Movies table that contains columns values of movie_id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  release_date DATE NOT NULL,
  director_id INT NOT NULL,
  actor_id INT NOT NULL,
  genre_id INT NOT NULL,
  running_time INT NOT NULL,
  rating_id INT NOT NULL,
  synopsis TEXT,
  PRIMARY KEY (movie_id),
  FOREIGN KEY (director_id) REFERENCES movies_Directors(director_id),
  FOREIGN KEY (actor_id) REFERENCES movies_Actors(actor_id),
  FOREIGN KEY (genre_id) REFERENCES movies_Genres(genre_id),
  FOREIGN KEY (rating_id) REFERENCES movies_Ratings(rating_id) based on the movieList, RatingsSource,  GenreSource, DirectorsSource, ActorsSource.